name: Release
on:
    release:
        types:
            - created
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2.3.4
            -   uses: actions/setup-java@v2
                with:
                    java-version: 11
                    distribution: 'zulu'
            -   run: ./ci/buildPlugin.sh
            -   name: Copy zip file
                run: cp build/distributions/*.zip image-icon-viewer.zip
            -   uses: actions/upload-release-asset@v1.0.2
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ github.event.release.upload_url }}
                    asset_path: image-icon-viewer.zip
                    asset_name: image-icon-viewer.zip
                    asset_content_type: application/zip
